language: node_js
sudo: false
node_js:
  - 0.12

env:
  global:
  - SAUCE_USERNAME=nathanboktae
  - secure: AqDqBanZz9tG5HsYyCPlpH2/RzHlMW4LQFVijfDpduPz7UXrZ4EqygPqfqI2WAgsee7Ce3TXZJ1S28JzUH8L70ELH7ruoy80umW12qNXaEt4SXBeuTlpTuEDfYurLN8DEHh3zmCh8136EwxhT4RaOWuA/R1PpbrymBygbPRLJMU=

script: npm test
